name: Trigger Central Workflow on Issue Creation

on:
  issues:
    types: [opened]

jobs:
  trigger-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Repository Dispatch
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            https://api.github.com/repos/Tanuj_D/.github/dispatches \
            -d '{
              "event_type": "issue_created",
              "client_payload": {
                "issue_data": {
                  "title": "${{ github.event.issue.title }}",
                  "html_url": "${{ github.event.issue.html_url }}",
                  "body": "${{ github.event.issue.body }}"
                }
              }
            }'
