name: Trigger Central Workflow on Issue Creation

on:
  issues:
    types: [opened]

jobs:
  trigger-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Repository Dispatch
        run: |
          payload=$(jq -n --arg title "${{ github.event.issue.title }}" \
                          --arg url "${{ github.event.issue.html_url }}" \
                          --arg body "${{ github.event.issue.body }}" \
            '{
              event_type: "issue_created",
              client_payload: {
                issue_data: {
                  title: $title,
                  html_url: $url,
                  body: $body
                }
              }
            }')

          curl -X POST \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Tanuj-D/main-repo/dispatches \
            -d "$payload"
